# NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [2]:
import numpy as np

In [7]:
na=np.array([3,2,9,2,6])

In [8]:
print(na)

[3 2 9 2 6]


In [9]:
type(na)

numpy.ndarray

In [10]:
na[0]

3

In [11]:
na[2]

9

In [9]:
na[:]

array([3, 2, 9, 2, 6])

In [11]:
na[ :3]

array([3, 2, 9])

In [12]:
na[1:3]

array([2, 9])

In [13]:
type(na[1])

numpy.int32

In [14]:
for i in  na:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [18]:
na=np.array([3,2.5,9,2,6])

In [19]:
for i in  na:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [20]:
for i in  na:
    print(i)

3.0
2.5
9.0
2.0
6.0


In [22]:
na=np.array([3,2.5,9,2,6,'hi'])

In [23]:
for i in  na:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# numpy array no mixed type is allowed, in list it is allowed

In [30]:
na1=np.append(10)

TypeError: _append_dispatcher() missing 1 required positional argument: 'values'

In [31]:
na1=np.append(na,10)

In [32]:
print(na1)

[3 2.5 9 2 6 'hi' list([1, 2, 3]) 10]


In [33]:
na2=np.append([3,4,5],10)

In [34]:
print(na2)

[ 3  4  5 10]


In [35]:
na2[0]

3

In [36]:
na2.max()

10

In [37]:
na2.min()

3

In [39]:
na=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
print(na)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
na.mean()

5.0

In [42]:
na.max()

9

In [43]:
na.min()

1

In [44]:
na.mean(axis=0)

array([4., 5., 6.])

In [45]:
na.mean(axis=1)

array([2., 5., 8.])

## 0 means column adding and dividing number ,, 1 means row adding and dividing

In [48]:
na=np.arange(2,12)

In [49]:
print(na)

[ 2  3  4  5  6  7  8  9 10 11]


In [50]:
na=np.arange(2,12,2)

In [51]:
print(na)

[ 2  4  6  8 10]


In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [54]:
np.twos(5)

AttributeError: module 'numpy' has no attribute 'twos'

In [2]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [3]:
np.linspace(0,20)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [4]:
np.linspace(10,30,5)# here 5 represents the numbers to give and also it will divide equaly

array([10., 15., 20., 25., 30.])

## difference between two numbers  is equal and it is always 50 numbers if we didn't mention numbers to give 

### the main difference b/w arange and linspace is in arange ending parameter is not included but in linspace it will give endingparameter

In [6]:
import numpy as np

In [7]:
na=np.array((3,2,6))

In [3]:
print(na)

[3 2 6]


In [4]:
na

array([3, 2, 6])

In [21]:
na=np.array({'a':10,'b':20})

In [22]:
print(na)

{'a': 10, 'b': 20}


In [25]:
na=np.array([4,5,6])

In [26]:
print(na)

[4 5 6]


In [27]:
na[0]

4

In [23]:
type(na)

numpy.ndarray

In [32]:
na=np.array((3,2,5))

In [33]:
na1=np.array(na)

In [34]:
print(na1)

[3 2 5]


In [35]:
na=np.eye(5)

In [36]:
print(na)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### this is called identity matrix

In [37]:
na=np.eye(5,3)

In [38]:
print(na)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


### create random numbers

In [5]:
na=np.random.random(30)

In [6]:
na

array([0.09692685, 0.38139413, 0.75976379, 0.22190527, 0.02282861,
       0.64493223, 0.19985876, 0.36213405, 0.2058986 , 0.06480363,
       0.03622117, 0.94807108, 0.06050731, 0.72979701, 0.70182634,
       0.36206403, 0.28368874, 0.24826931, 0.2931742 , 0.14025965,
       0.25174408, 0.85095677, 0.74170515, 0.06306901, 0.32496942,
       0.85301357, 0.72322926, 0.38290719, 0.52781032, 0.58252607])

In [13]:
na=np.random.random((5,4))

In [14]:
na

array([[0.1559161 , 0.49839195, 0.23181784, 0.42185467],
       [0.56068509, 0.17417728, 0.59306787, 0.04744347],
       [0.1978677 , 0.63308997, 0.04172838, 0.9957244 ],
       [0.29239244, 0.64860132, 0.27539367, 0.88444388],
       [0.31782101, 0.07134918, 0.27728953, 0.27516289]])

In [17]:
na1=np.round(na,3)

In [19]:
na1

array([[0.156, 0.498, 0.232, 0.422],
       [0.561, 0.174, 0.593, 0.047],
       [0.198, 0.633, 0.042, 0.996],
       [0.292, 0.649, 0.275, 0.884],
       [0.318, 0.071, 0.277, 0.275]])

In [3]:
np.random.rand(5)

array([0.9767282 , 0.79513323, 0.07032061, 0.42579767, 0.43627098])

In [4]:
np.random.rand(30)

array([0.28464138, 0.779488  , 0.99633023, 0.33462595, 0.04760644,
       0.70113105, 0.02345978, 0.0537932 , 0.10698974, 0.07498967,
       0.53616369, 0.72707875, 0.74928628, 0.58723669, 0.85318925,
       0.41605085, 0.91613495, 0.56092483, 0.80710265, 0.54465982,
       0.94464572, 0.59307442, 0.60384202, 0.51127235, 0.73099173,
       0.74222251, 0.53347331, 0.37294832, 0.72678968, 0.91600272])

### give random numbers but between 0-1

In [10]:
np.random.rand(3,4)

array([[0.44660955, 0.48739467, 0.81335812, 0.37210285],
       [0.7162473 , 0.34027912, 0.08015813, 0.36327804],
       [0.72175432, 0.59734961, 0.81095693, 0.37222678]])

In [41]:
np.random.randn(6)

array([-1.58419016,  0.48119658,  0.32812955,  0.45047377, -1.20529504,
       -0.36709003])

In [5]:
np.random.randn(30)

array([-1.12944847,  0.75312858,  0.17651368,  0.51754278,  0.26797814,
       -1.59905254,  2.84184406,  0.33132196, -1.10814584, -0.33599409,
        2.92605029, -0.01475593,  2.70072752,  0.18390445, -0.14874706,
        0.78364809, -0.45054969,  1.07256314, -0.25355006,  1.81239726,
       -1.90231954,  0.33327774,  0.4312054 ,  0.87664271,  0.31862465,
       -0.20950886,  0.47246925,  0.30284648,  0.26521314,  0.15970528])

In [6]:
np.random.randn(4,3)

array([[ 0.2368491 , -1.81078706, -0.12811022],
       [-0.2262414 , -0.34109859,  0.04391136],
       [ 2.85028068, -1.22907801,  0.03780198],
       [ 1.767709  , -0.83666308,  0.93846983]])

#### randn no limit

In [47]:
np.random.randint(6)

1

In [51]:
np.random.randint(5,15)

13

In [52]:
np.random.randint(5,15,20)

array([14,  5,  5, 12, 11,  7,  5, 14, 14,  9,  5, 14, 14,  7, 10, 12,  8,
        9, 13, 11])

#### 1st parameter is integer lower to higher-1,,,6 means (0,5)
     2nd parameter range
     3rd one is size

In [7]:
na=np.arange(42)

In [8]:
print(na)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]


In [9]:
na[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
na.shape

(42,)

In [72]:
na.shape=(6,7)

In [73]:
print(na)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [77]:
na[1:4,1:3]

array([[ 8,  9],
       [15, 16],
       [22, 23]])

In [82]:
na[2:5,2:6]

array([[16, 17, 18, 19],
       [23, 24, 25, 26],
       [30, 31, 32, 33]])

In [21]:
na=np.arange(42)

In [22]:
print(na)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]


In [23]:
na.reshape(6,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

## shape is a parameter reshape is a function

In [25]:
na.reshape(7,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [26]:
na.reshape(-1,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [27]:
na.reshape(-1,-1)

ValueError: can only specify one unknown dimension

## can only specify one unknown value

In [89]:
na=np.arange(42)

In [90]:
print(na)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]


In [28]:
na=np.random.randint(2,100,30)

In [29]:
print(na)

[69 15  4 75 51 81 35 98 54 60 34 19 36 26 49 57 70 79 36 89 81 86 94 50
  2  8 55 20 16 91]


In [30]:
na.max()

98

In [31]:
na.min()

2

In [32]:
na.mean()

51.333333333333336

In [33]:
na.argmax()

7

### argmax is in 7th position

In [34]:
na.argmin()

24

In [35]:
na.all()

True

In [37]:
na=np.random.random((5,6))

In [38]:
na

array([[0.49451757, 0.32298093, 0.53820414, 0.90061516, 0.53357356,
        0.22586203],
       [0.57262469, 0.21338994, 0.30277085, 0.12661912, 0.28073753,
        0.96163291],
       [0.41764702, 0.74393225, 0.12134472, 0.25170893, 0.03795277,
        0.9228185 ],
       [0.51335207, 0.28774913, 0.08308213, 0.69212567, 0.2370346 ,
        0.40340868],
       [0.56668736, 0.85154938, 0.94077209, 0.47950714, 0.1231387 ,
        0.5646777 ]])

In [39]:
na.max()

0.9616329146964702

In [40]:
na.min()

0.03795277031585487

In [42]:
na.max(axis=0)

array([0.57262469, 0.85154938, 0.94077209, 0.90061516, 0.53357356,
       0.96163291])

In [43]:
na.argmax()

11

In [44]:
na.argmax(axis=0)

array([1, 4, 4, 0, 0, 1], dtype=int64)

In [23]:
na=np.random.randint(0,100,30)

In [24]:
print(na)

[39 29 75 57 78 82 88 15 91 38 10 98 34 87 98 27 40 87 46  9 79 38 74 35
 24 24 59 25 89  0]


In [25]:
na.all()

False

## if zero is there thn it is false

In [127]:
na1=np.array([0,1,0])

In [128]:
na1.all()

False

In [129]:
na1.any()

True

## any means any one element is 1 thn it is true everything is 0 thn it is false

In [11]:
na=np.array([3,5,76,5,32,4,5,89,66,22,11])

In [12]:
np.flip(na)

array([11, 22, 66, 89,  5,  4, 32,  5, 76,  5,  3])

In [13]:
#another way
na[::-1]

array([11, 22, 66, 89,  5,  4, 32,  5, 76,  5,  3])

In [14]:
#reverse slicing

In [15]:
na.argpartition(0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [136]:
na.argpartition(1)

array([ 8,  9,  2,  3,  4,  5,  6,  7,  0,  1, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64)

In [137]:
na.argpartition(2)

array([ 8,  9,  0,  3,  4,  5,  6,  7,  2,  1, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64)

In [138]:
na.argpartition(3)

array([ 0,  9,  8, 23, 24, 16, 15,  7, 28,  1, 14, 11, 12, 13, 10,  6,  5,
       17, 18, 19, 20, 21, 22,  4,  3, 25, 26, 27,  2, 29], dtype=int64)

In [139]:
na.argpartition(4)

array([ 0,  9,  8, 23, 24, 15, 16,  7, 28,  1, 14, 11, 12, 13, 10,  6,  5,
       17, 18, 19, 20, 21, 22,  4,  3, 25, 26, 27,  2, 29], dtype=int64)

In [140]:
na.argpartition(5)

array([ 0,  9,  8, 23, 24, 15, 16,  7, 28,  1, 14, 11, 12, 13, 10,  6,  5,
       17, 18, 19, 20, 21, 22,  4,  3, 25, 26, 27,  2, 29], dtype=int64)

In [144]:
na.argpartition(6)

array([ 0,  9,  8, 23, 24, 15, 16,  7, 28,  1, 14, 11, 12, 13, 10,  6,  5,
       17, 18, 19, 20, 21, 22,  4,  3, 25, 26, 27,  2, 29], dtype=int64)

In [145]:
na.argpartition(7)

array([ 0,  9,  8, 23, 24, 15, 16,  7, 28,  1, 14, 11, 12, 13, 10,  6,  5,
       17, 18, 19, 20, 21, 22,  4,  3, 25, 26, 27,  2, 29], dtype=int64)

In [148]:
na

array([10, 40, 48, 78, 62, 62, 52, 35,  0,  5, 87, 48, 59, 95, 44, 29, 30,
       75, 84, 92, 45, 70, 59, 10, 27, 66, 77, 50, 35, 91])

In [152]:
na.argsort()

array([ 8,  9,  0, 23, 24, 15, 16, 28,  7,  1, 14, 20,  2, 11, 27,  6, 22,
       12,  5,  4, 25, 21, 17, 26,  3, 18, 10, 29, 19, 13], dtype=int64)

## argsort is sorting in position incresing order

In [154]:
na.astype(float)

array([10., 40., 48., 78., 62., 62., 52., 35.,  0.,  5., 87., 48., 59.,
       95., 44., 29., 30., 75., 84., 92., 45., 70., 59., 10., 27., 66.,
       77., 50., 35., 91.])

In [155]:
na

array([10, 40, 48, 78, 62, 62, 52, 35,  0,  5, 87, 48, 59, 95, 44, 29, 30,
       75, 84, 92, 45, 70, 59, 10, 27, 66, 77, 50, 35, 91])

In [156]:
na.astype(str)

array(['10', '40', '48', '78', '62', '62', '52', '35', '0', '5', '87',
       '48', '59', '95', '44', '29', '30', '75', '84', '92', '45', '70',
       '59', '10', '27', '66', '77', '50', '35', '91'], dtype='<U11')

In [5]:
na=np.array([[3,4,5],[34,45,66],[53,2,21]])

In [4]:
np.choose([2,1,0],na)

array([53, 45,  5])

In [6]:
na

array([[ 3,  4,  5],
       [34, 45, 66],
       [53,  2, 21]])

In [7]:
na.clip(5,50)

array([[ 5,  5,  5],
       [34, 45, 50],
       [50,  5, 21]])

# below 5 above 50 will be replaced with 5 and 50.

In [23]:

na

array([[ 3,  4,  5],
       [34, 45, 66],
       [53,  2, 21]])

In [31]:
na.fill(0)

In [32]:
print(na)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [33]:
print(na2)

[39 29 75 57 78 82 88 15 91 38 10 98 34 87 98 27 40 87 46  9 79 38 74 35
 24 24 59 25 89  0]


In [78]:
na1=np.random.randint(0,100,30)

In [79]:
print(na1)

[84 28 28 87 58 21 95 34 10 95 47 94 41 14 26 37 82 66 37 82  9 72 21 69
 40 53 38 37 26 99]


In [46]:
na1.cumprod()

array([         95,        4180,      234080,    23173920,  1575826560,
        1636139648, -1433535872, -1529421312, -1759779840,  1281399808,
        -592575488, -1645247488, -1385390080, -1660403712, -1814134784,
        1968406528,  1246330880, -1551990784,  1008828416,  2128379904,
        -840564736,  -206831616, -2006974464,  1686110208,   696254464,
         335544320,  1879048192, -1610612736,  1073741824, -1073741824],
      dtype=int32)

### cumprod is cumulative product multiply the next element

In [48]:
na1.cumsum()

array([  95,  139,  195,  294,  362,  423,  472,  524,  542,  573,  596,
        693,  733,  759,  817,  868,  921,  968, 1031, 1114, 1158, 1240,
       1312, 1324, 1383, 1439, 1483, 1537, 1611, 1702], dtype=int32)

### cumsum is a cumulative sum add the next element

In [28]:
na=np.array([[3,4,5],[6,7,8],[9,34,6]])

In [29]:
print(na)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 34  6]]


In [30]:
na.diagonal()

array([3, 7, 6])

In [31]:
na.diagonal(1)

array([4, 8])

In [32]:
na.diagonal(0)

array([3, 7, 6])

In [34]:
 na.dot(2)

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 68, 12]])

In [80]:
print(na1)

[84 28 28 87 58 21 95 34 10 95 47 94 41 14 26 37 82 66 37 82  9 72 21 69
 40 53 38 37 26 99]


In [81]:
na1.dot(2)

array([168,  56,  56, 174, 116,  42, 190,  68,  20, 190,  94, 188,  82,
        28,  52,  74, 164, 132,  74, 164,  18, 144,  42, 138,  80, 106,
        76,  74,  52, 198])

### dot it is a product of two array

In [234]:
na=np.array([1,2,3,4,5,6,7])

In [235]:
na.item(3)

4

In [237]:
na.item(6)

7

## position of an element

In [4]:
na1=np.array([[1,2,3],[4,5,6],[6,5,4]])

In [241]:
na1.item(3)

4

In [244]:
na1.item(5)

6

In [246]:
na1.item((1,2))

6

In [249]:
na1.item((2,2))

4

## item means gives the position in case of 2 elements one will define row number and other position or index

In [8]:
na=np.random.randint(0,100,30)

In [10]:
print(na)

[78 26 33 19 58 91 70 76 11 42 33 66 45 45 33 53 93 62 37 69 85 90 18 69
  8 54 65  2  1 38]


In [15]:
bytes=na.nbytes

In [16]:
bytes

120

In [31]:
na=np.array([[2,3,4],[3,6,8],[6,9,3]])

In [32]:
na.nbytes

36

In [33]:
na=np.array([3,4,5,6,7,8,9,3,4,6,7,7,7,8,4])

In [34]:
na.nbytes

60

## Total bytes consumed by the elements of the array.

In [35]:
na=np.array([[3,4,5],[4,8,7]])

In [36]:
na.ndim

2

## ndim means Number of array dimensions (how many dimensions are there)

In [37]:
na=np.random.rand(3,3)

In [38]:
print(na)

[[0.96675351 0.25756248 0.4558398 ]
 [0.43743558 0.45992946 0.63009138]
 [0.98962018 0.01637716 0.31440563]]


In [39]:
na=np.array([[3,4,5],[4,8,7]])

In [40]:
na.newbyteorder()

array([[ 50331648,  67108864,  83886080],
       [ 67108864, 134217728, 117440512]])

In [43]:
na=np.array([9,8])

In [44]:
na.newbyteorder()

array([150994944, 134217728])

In [58]:
na=np.array([[3,4,5],[4,8,7]])

In [59]:
na

array([[3, 4, 5],
       [4, 8, 7]])

In [60]:
na.nonzero()

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [51]:
na=np.array([3,4,5,6,7,7,2])

In [52]:
na.nonzero()

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)

In [61]:
na=np.array([1,3,0,10,6,4])

In [56]:
na.nonzero()

(array([0, 1, 3, 4, 5], dtype=int64),)

## Return the indices of the elements that are non-zero.

In [107]:
na=np.array([1,2,5,8,4,9,5,3,0,10,6,4])

In [108]:
na

array([ 1,  2,  5,  8,  4,  9,  5,  3,  0, 10,  6,  4])

In [109]:
na.partition(6)

In [110]:
na

array([ 2,  1,  0,  3,  4,  4,  5,  5,  8, 10,  6,  9])

In [111]:
na.partition(5)

In [112]:
na

array([ 1,  2,  0,  3,  4,  4,  5,  5,  6,  8, 10,  9])

In [113]:
na.partition(9)

In [114]:
na

array([ 2,  1,  0,  3,  4,  5,  4,  5,  6,  8,  9, 10])

## Rearranges the elements in the array in such a way that the value of the element in kth position is in the position it would be in a sorted array. All elements smaller than the kth element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.

In [116]:
na=np.array([[2,3,4],[5,6,7]])

In [117]:
na.prod()

5040

In [118]:
na=np.array([[2,3,4],[5,0,7]])

In [119]:
na.prod()

0

### 0 product anything return zero

## Return the product of the array elements over the given axis

In [120]:
na=np.array([[2,3,4],[5,6,7]])

In [121]:
na.ptp()

5

In [122]:
na=np.array([[1,3,4],[5,10,7]])

In [123]:
na.ptp()

9

## Peak to peak (maximum - minimum) value along a given axis.

In [8]:
na=np.array([[1,3,4],[5,10,7]])

In [10]:
na.put(4,3)

In [11]:
na

array([[1, 3, 4],
       [5, 3, 7]])

In [131]:
na.put(5,99)

In [132]:
na

array([[ 1,  3,  4],
       [ 5,  3, 99]])

In [133]:
na.ravel()

array([ 1,  3,  4,  5,  3, 99])

## Return a flattened array.

In [135]:
na.repeat(5)

array([ 1,  1,  1,  1,  1,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  5,  5,
        5,  5,  5,  3,  3,  3,  3,  3, 99, 99, 99, 99, 99])

## Repeat elements of an array.

In [141]:
na=np.array([[4,5,6],[4,2,6],[7,2,8],[3,9,7]])

In [142]:
na

array([[4, 5, 6],
       [4, 2, 6],
       [7, 2, 8],
       [3, 9, 7]])

In [143]:
na.reshape(3,4)

array([[4, 5, 6, 4],
       [2, 6, 7, 2],
       [8, 3, 9, 7]])

In [144]:
na

array([[4, 5, 6],
       [4, 2, 6],
       [7, 2, 8],
       [3, 9, 7]])

## Returns an array containing the same data with a new shape.



In [12]:
na=np.array([[4,5,6],[4,2,6],[7,2,8],[3,9,7],[3,6,4]])

In [13]:
na

array([[4, 5, 6],
       [4, 2, 6],
       [7, 2, 8],
       [3, 9, 7],
       [3, 6, 4]])

In [14]:
na.resize(3,5)

In [15]:
na

array([[4, 5, 6, 4, 2],
       [6, 7, 2, 8, 3],
       [9, 7, 3, 6, 4]])

In [16]:
na

array([[4, 5, 6, 4, 2],
       [6, 7, 2, 8, 3],
       [9, 7, 3, 6, 4]])

## Return a new array with the specified shape.



In [169]:
na=np.array([2.0,3.5,4,5,7.6,7,9.51,5.3])

In [170]:
na

array([2.  , 3.5 , 4.  , 5.  , 7.6 , 7.  , 9.51, 5.3 ])

In [172]:
na.round()

array([ 2.,  4.,  4.,  5.,  8.,  7., 10.,  5.])

## Return a with each element rounded to the given number of decimals.

In [66]:
na=np.array((4,5,6))

In [67]:
na.size

3

## Number of elements in the array.

In [153]:
na=np.zeros((4,5,6))

In [154]:
na

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [155]:
na.size

120

In [17]:
na=np.array((4,8,1,3,0,6,2,8))

In [18]:
na.sort()

In [19]:
print(na)

[0 1 2 3 4 6 8 8]


In [163]:
na[0]

4

In [180]:
na.std()

2.6246692913372702

## Returns the standard deviation of the array elements along given axis.

In [194]:
na=np.array([8,8,1,3,0,6,2,8])

In [195]:
na

array([8, 8, 1, 3, 0, 6, 2, 8])

In [196]:
na.std()

3.1622776601683795

## std=standard deviation

In [3]:
import numpy as np

In [4]:
na=np.array([[4,8,1],[3,0,6]])

In [5]:
na

array([[4, 8, 1],
       [3, 0, 6]])

In [207]:
na.sum(0)

array([7, 8, 7])

In [102]:
na=np.array([4,8,1,3,0,7,4,8,3,5,8,26])

In [104]:
na.sum()

77

In [208]:
na=np.array([[4,8,1],[3,0,6]])

In [209]:
print(na)

[[4 8 1]
 [3 0 6]]


In [210]:
na.swapaxes(1,0)

array([[4, 3],
       [8, 0],
       [1, 6]])

In [211]:
na.swapaxes(0,0)

array([[4, 8, 1],
       [3, 0, 6]])

## Return a view of the array with axis1 and axis2 interchanged.

In [212]:
na=np.array([[4,8,1],[3,0,6]])

In [215]:
na

array([[4, 8, 1],
       [3, 0, 6]])

In [216]:
na.take(2)

1

In [217]:
na.take(4)

0

## Return an array formed from the elements of a at the given indices.

In [130]:
na=np.array([[4.0,8.4,1],[3,0,6]])

In [131]:
na.tolist()

[[4.0, 8.4, 1.0], [3.0, 0.0, 6.0]]

## Return the array as an a.ndim-levels deep nested list of Python scalars.

In [134]:
na.tostring()

C:\Users\sindhu b\AppData\Local\Temp\ipykernel_10724\3562224894.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  na.tostring()


b'\x04\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00'

In [219]:
na

array([[4, 8, 1],
       [3, 0, 6]])

In [220]:
na.transpose()

array([[4, 3],
       [8, 0],
       [1, 6]])

In [136]:
na

array([[4, 8, 1],
       [3, 0, 6]])

In [223]:
na.put(3,8)

In [224]:
na

array([[4, 8, 1],
       [8, 0, 6]])

In [225]:
na.put(0,99)

In [226]:
na

array([[99,  8,  1],
       [ 8,  0,  6]])

In [261]:
na1=np.array([3,5,4,3])

In [262]:
na2=np.array([4,3,2,4])

In [266]:
na3=np.concatenate((na1,na2))

In [267]:
print(na3)

[3 5 4 3 4 3 2 4]


### we should pass through tuple

In [268]:
na4=np.append(na1,na2)

In [269]:
print(na4)

[3 5 4 3 4 3 2 4]


### here no need directly we can pass

In [270]:
na1=np.array([3,5,4,3,4,7,8,9])

In [271]:
n=np.array_split(na1,3)

In [272]:
print(n)

[array([3, 5, 4]), array([3, 4, 7]), array([8, 9])]


### split the number of arrays

In [273]:
n=np.array_split(na1,4)

In [274]:
print(n)

[array([3, 5]), array([4, 3]), array([4, 7]), array([8, 9])]


In [303]:
na=np.array(['hi','hello','Good'])

In [304]:
print(na)

['hi' 'hello' 'Good']


In [309]:
np.sort(na)

array(['Good', 'hello', 'hi'], dtype='<U5')

In [305]:
na1=np.array([3,5,4,3,4,7,8,7,0,2,1])

In [306]:
x=np.sort(na1)

In [307]:
print(x)

[0 1 2 3 3 4 4 5 7 7 8]


In [319]:
na1=np.array([3,5,4,3,4,7,8,7,0,2,1])

In [321]:
na1[2:7]

array([4, 3, 4, 7, 8])

In [322]:
na1[2:7]=99

In [323]:
print(na1)

[ 3  5 99 99 99 99 99  7  0  2  1]


### this is called broadcasting

In [373]:
na1=np.array([[3,5,4],[7,8,7]])

In [374]:
na1

array([[3, 5, 4],
       [7, 8, 7]])

In [376]:
na1[0:2]

array([[3, 5, 4],
       [7, 8, 7]])

In [377]:
na1[0:5]=77

In [378]:
print(na1)

[[77 77 77]
 [77 77 77]]


In [341]:
na1[0:2]

array([[3, 5, 4],
       [7, 8, 7]])

In [342]:
na1[0:2]=66

In [343]:
print(na1)

[[66 66 66]
 [66 66 66]]


In [345]:
na1[0:1]=66

In [346]:
print(na1)

[[66 66 66]
 [ 7  8  7]]


In [362]:
na1[0:2,1:3]=55

In [363]:
print(na1)

[[ 3 55 55]
 [ 7 55 55]]


In [367]:
na1=np.array([[3,5,4,7,8,7]])

In [368]:
na1>2

array([[ True,  True,  True,  True,  True,  True]])

In [369]:
na1>3

array([[False,  True,  True,  True,  True,  True]])

In [384]:
na1=np.array([3,4,5,6,7])

In [381]:
na2=np.array([4,5,9,8,2])

In [382]:
na1+na2

array([ 7,  9, 14, 14,  9])

In [385]:
na1**3

array([ 27,  64, 125, 216, 343], dtype=int32)

In [386]:
np.sqrt(na1)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131])

In [395]:
na1=np.array([4,16,64])

In [389]:
np.sqrt(na1)

array([2., 4., 8.])

In [391]:
np.sin(90)

0.8939966636005579

In [393]:
np.sin(30)

-0.9880316240928618

In [397]:
np.log(na1)

array([1.38629436, 2.77258872, 4.15888308])